services:
  beary:
    build: beary
    ports:
      - "2022:22"
    networks:
      bearly-awake-network:

  webserver:
    build: webserver
    networks:
      bearly-awake-network:

networks:
  bearly-awake-network:
