from ubuntu:latest

EXPOSE 12366
EXPOSE 12367

ADD ./UnitedSlots1 /home/ubuntu/UnitedSlots1
ADD ./UnitedSlots2 /home/ubuntu/UnitedSlots2

CMD /home/ubuntu/UnitedSlots1 12366 & /home/ubuntu/UnitedSlots2 12367
