management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    env:
      enabled: true
      show-values: always
