services:
  user:
    build: user
    mac_address: 00:00:00:00:00:01
    networks:
      arpacadabra:
        ipv4_address: 172.80.183.2
    environment:
      - WEBSERVER_IP=172.80.183.3

  webserver:
    build: webserver
    mac_address: 00:00:00:00:00:02
    networks:
      arpacadabra:
        ipv4_address: 172.80.183.3

  attacker:
    build: attacker
    mac_address: 00:00:00:00:00:03
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      arpacadabra:
        ipv4_address: 172.80.183.4

networks:
  arpacadabra:
    # internal: true
    ipam:
      config:
        - subnet: 172.80.183.0/24
