services:
  user:
    build: user
    networks:
      arpacadabra:

  webserver:
    build: webserver
    ports:
      - "8080:80"
    networks:
      arpacadabra:

  attacker:
    build: attacker
    ports:
      - "2022:22"
    networks:
      arpacadabra:

networks:
  arpacadabra:
