services:
  beary:
    build: beary
    networks:
      bearly-awake-network:
        ipv4_address: <IP>

  webserver:
    build: webserver
    networks:
      bearly-awake-network:
        ipv4_address: <IP>

networks:
  bearly-awake-network:
    internal: true
    ipam:
      config:
        - subnet: 172.99.53.0/24
